version: "3.2"
services:
  server:
    container_name: nodeapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
      - db
    networks:
      - backend
  db: 
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
      - redis
    networks:
      - backend
  redis:
    image: redis:7.0.0
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - cache:/data
    networks:
      - backend
networks:
  backend:
    driver: bridge
volumes:
  cache:
      driver: local
  pgdata: